### ISSUE TITLE
Resolve returns non existent ipv6 address for localhost

### ISSUE THREAD

**Issue by jakobod** [actor-framework/incubator#21]
The `net::ip::resolve()` call resolves "localhost" to an ipv4 and an ipv6 address even though the actual interface does not have an ipv6 address.

I would expect that `resolve()` only returns an ipv4 address.

I've tested this on mobi7 with the caf-jenkins-fedora-28 docker image. `ip a` gives me:
```
[root@110ca512e5fc incubator]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
4586: eth0@if4587: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:11:00:04 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.4/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```
The result of resolve is a vector containing the addresses:
```
  -> 127.0.0.1 [line 47]
  -> ::1 [line 47]
```

**Comment by jakobod** [comment]
@josephnoir would you mind taking a look at this?

**Comment by josephnoir** [comment]
Yeah. The function just returns both addresses if you put in `"localhost"`. It should probably check first if the specific version is supported at all.

**Comment by josephnoir** [comment]
The right approach would be using the `local_addresses` function I started implementing [here](https://github.com/actor-framework/incubator/tree/topic/ifaddrs). That will resolve `localhost` to the correct addresses.

I'm still working on the Windows implementation. I'll try to get that done some time next week.

**Comment by jakobod** [comment]
Awesome, thank you @josephnoir . I will update to using `local_addresses()` as soon as its done. 😋

**Comment by josephnoir** [comment]
Wait, `resolve` doesn't actually have anything hard coded ([it's just calling getaddrinfo](https://github.com/actor-framework/incubator/blob/master/libcaf_net/src/ip.cpp#L86). The results of that call depend on `/etc/hosts` which includes `::1` in the Docker images. Meaning, this is a configuration problem and not actually a failure.

Maybe we can get around this by checking the `lo` interface in `local_addresses`, or better, when `local_addresses` gets passed "localhost" we perform a resolve call and then check if any of the interfaces actually has that address.
