### ISSUE TITLE
Code duplication in different transport implementations

### ISSUE THREAD

**Issue by jakobod** [actor-framework/incubator#36]
While going through the different transport implementations I noticed that we currently duplicate a lot of code.
I think we can clean up those implementations by supplying something like a `transport_base`, which encapsulates the shared state and functions. The different transport-implementations would only need to implement their individual `init()`, `handle_read_event()` and `handle_write_event()` functions + special state/functions.

Would that be a good idea? Or is there something that speaks against such a change @Neverlord ?

**Comment by Neverlord** [comment]
> Would that be a good idea?

Reducing code duplication? For sure! Go for it! 👍

**Comment by jakobod** [comment]
I'll start with that when the `datagram_transport` is merged.
